------------
--APORTANTES
------------
CREATE TABLE public.APORTANTES (
                ID BIGINT IDENTITY NOT NULL,
                ESTADO BIGINT NOT NULL,
                CIUDAD_MUNICIPIO CHAR(3) NOT NULL,
                DEPARTAMENTO CHAR(2) NOT NULL,
                TIPO_ACCION INTEGER,
                TIPO_APORTANTE CHAR(1) NOT NULL,
                ADM_RIESGOS_LABORALES CHAR(6) NOT NULL,
                ADM_CAJA_COMPENSACION CHAR(6),
                ACTIVIDAD_ECONOMICA CHAR(4) NOT NULL,
                FORMA_PAGO CHAR(1) NOT NULL,
                FORMA_PRESENTACION CHAR(1) NOT NULL,
                TIPO_PERSONA CHAR(1) NOT NULL,
                NATURALEZA_JURIDICA INTEGER NOT NULL,
                CLASE_APORTANTE CHAR(1) NOT NULL,
                TIPO_IDENTIFICACION CHAR(2) NOT NULL,
                NRO_IDENTIFICACION CHAR(16) NOT NULL,
                DIGITO_VERIFICACION INTEGER,
                NOMBRE_RAZON_SOCIAL CHAR(200) NOT NULL,
                APORTA_ESAP_MINEDU BOOLEAN,
                LEY_HABEAS_DATA BOOLEAN NOT NULL,
                EXONERADO_PAGO_PARAF_SALUD BOOLEAN,
                ENVIO_SOPORTE_PAGO_APORTANTE BOOLEAN NOT NULL,
                ENVIO_SOPORTE_PAGO_COTIZANTES BOOLEAN NOT NULL,
                CORREO_ELECTRONICO CHAR(60) NOT NULL,
                TELEFONO CHAR(10) NOT NULL,
                TERMINO_ACTIVIDADES_COMERCIALES DATE,
                CONCORDATO_REESTRUCTU_LIQUIDAC_CESE DATE,
                DIRECCION_CORRESPONDENCIA CHAR(40) NOT NULL,
                FAX CHAR(10),
                REP_LEGAL_PRIMER_NOMBRE CHAR(20) NOT NULL,
                REP_LEGAL_SEGUNDO_NOMBRE CHAR(30),
                REP_LEGAL_PRIMER_APELLIDO CHAR(20) NOT NULL,
                REP_LEGAL_SEGUNDO_APELLIDO CHAR(30),
                REP_LEGAL_TIPO_IDENTIFICACION CHAR(2) NOT NULL,
                REP_LEGAL_NRO_IDENTIFICACION CHAR(16) NOT NULL,
                REP_LEGAL_DIGITO_VERIFICACION INTEGER NOT NULL,
                CONSTRAINT aportantes_id_pkey PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX aportantes_tipoid_nroid_key
 ON public.APORTANTES
 ( TIPO_IDENTIFICACION, NRO_IDENTIFICACION ); 

-------------------------
--SUCURSALES DE APORTANTE
-------------------------
CREATE TABLE public.SUCURSALES_APORTANTE (
                ID BIGINT IDENTITY NOT NULL,
                TIPO_IDENTIFICACION CHAR(2) NOT NULL,
                NRO_IDENTIFICACION CHAR(16) NOT NULL,
                CODIGO_SUCURSAL CHAR(10) NOT NULL,
                NOMBRE_SUCURSAL CHAR(40) NOT NULL,
                CONSTRAINT sucursales_aportante_pk PRIMARY KEY (ID)
);

ALTER TABLE public.SUCURSALES_APORTANTE
   ADD CONSTRAINT sucursales_aportante_fk
   FOREIGN KEY(TIPO_IDENTIFICACION, NRO_IDENTIFICACION)
   REFERENCES public.APORTANTES(TIPO_IDENTIFICACION, NRO_IDENTIFICACION);


CREATE UNIQUE INDEX sucursales_aportante_key
 ON public.SUCURSALES_APORTANTE
 ( TIPO_IDENTIFICACION, NRO_IDENTIFICACION, CODIGO_SUCURSAL );

------------
--COTIZANTES
------------
CREATE TABLE COTIZANTES (
                ID BIGINT IDENTITY NOT NULL,
                NRO_IDENTIFICACION CHAR(16) NOT NULL,
                TIPO_IDENTIFICACION CHAR(2) NOT NULL,
                SUCURSAL BIGINT NOT NULL,
                TIPO_COTIZANTE CHAR(2) NOT NULL,
                SUBTIPO_COTIZANTE CHAR(2) NOT NULL,
                EXTRANJERO_NO_OBLIGADO_COTIZAR_PENSION BOOLEAN NOT NULL,
                COLOMBIANO_RESIDENTE_EXTERIOR BOOLEAN NOT NULL,
                DEPARTAMENTO CHAR(2) NOT NULL,
                CIUDAD_MUNICIPIO CHAR(3) NOT NULL,
                PRIMER_NOMBRE CHAR(20) NOT NULL,
                SEGUNDO_NOMBRE CHAR(30),
                PRIMER_APELLIDO CHAR(20) NOT NULL,
                SEGUNDO_APELLIDO CHAR(30),
                ADM_PENSION CHAR(6),
                ADM_SALUD CHAR(6),
                ADM_CAJA_COMPENSACION CHAR(6),
                SALARIO_BASICO INTEGER NOT NULL,
                SALARIO_INTEGRAL BOOLEAN NOT NULL,
                TARIFA_PENSION DOUBLE PRECISION NOT NULL,
                TARIFA_SALUD DOUBLE PRECISION NOT NULL,
                TARIFA_CAJA_COMPENSACION DOUBLE PRECISION NOT NULL,
                TARIFA_SENA DOUBLE PRECISION NOT NULL,
                TARIFA_ICBF DOUBLE PRECISION NOT NULL,
                TARIFA_ESAP DOUBLE PRECISION NOT NULL,
                TARIFA_MINEDU DOUBLE PRECISION NOT NULL,
                EXONERADO_PAGO_PARAF_SALUD BOOLEAN NOT NULL,
                ESTADO BIGINT NOT NULL,
                CORREO_ELECTRONICO CHAR(60),
                CORREO_ELECTRONICO_CC CHAR(60),
                FECHA_INGRESO_LABORAL DATE NOT NULL,
                TIPO_SOPORTE_PAGO BIGINT NOT NULL,
                ADM_RIESGOS_LABORALES CHAR(6),
                CENTRO_TRABAJO BIGINT,							--<<<<<<<<<<<<<<<<<<<< XXX TODO ESTE CAMPO PUEDE SER NULL O NO?
                CONSTRAINT cotizantes_pk PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX cotizantes_tipoid_nroid_sucursal_key
 ON public.COTIZANTES
 ( NRO_IDENTIFICACION, TIPO_IDENTIFICACION, SUCURSAL );
 
 ------------
--NOVEDADES
------------
CREATE TABLE NOVEDADES (
                ID BIGINT IDENTITY NOT NULL,
                PERIODO_MES INTEGER NOT NULL,
                PERIODO_ANIO INTEGER NOT NULL,
                INCAPACIDAD_GENERAL BIGINT,
                RETIRO BIGINT,
                INGRESO BIGINT,
                LICENCIA_MATERNIDAD BIGINT,
                VARIACION_PERMANENTE_SALARIO BIGINT,
                VARIACION_TRANSITORIA_SALARIO BIGINT,
                VACACIONES BIGINT,
                TRASLADO_EPS BIGINT,
                TRASLADO_AFP BIGINT,
                APORTE_VOLUNTARIO BIGINT,
                INCAPACIDAD_PROFESIONAL BIGINT,
                VARIACION_CENTROS_TRABAJO BIGINT,
                SUSPENSION_TEMPORAL_CONTRATO BIGINT,
                COTIZANTE_ID BIGINT NOT NULL,
                CONSTRAINT novedades_pk PRIMARY KEY (ID)
);

CREATE TABLE NOVEDADES_SUSPENSION_TEMPORAL_CONTRATO (
                ID BIGINT IDENTITY NOT NULL,
                DIA_INICIO_SUSPENSION_TEMPORAL_CONTRATO CHAR(2) NOT NULL,
                FECHA_FINAL_SUSPENSION_TEMPORAL DATE NOT NULL,
                ES_NOVEDAD_COMISION_SERVICIOS BOOLEAN NOT NULL,
                SALARIO_BASICO_ANTERIOR INTEGER NOT NULL,
                TARIFA_SALUD DOUBLE PRECISION NOT NULL,
                TARIFA_PENSION DOUBLE PRECISION NOT NULL,
                CONSTRAINT novedades_suspension_temporal_contrato_pk PRIMARY KEY (ID)
);

CREATE TABLE NOVEDADES_VARIACION_TRANSITORIA_DEL_SALARIO (
                ID BIGINT IDENTITY NOT NULL,
                VALOR_VARIACION_TRANSITORIA_SALARIO VARCHAR NOT NULL,
                CONSTRAINT novedades_variacion_transitoria_del_salario_pk PRIMARY KEY (ID)
);

CREATE TABLE NOVEDADES_VARIACION_PERMANENTE_SALARIO (
                ID BIGINT IDENTITY NOT NULL,
                VALOR_VARIACION_PERMANENTE_SALARIO INTEGER NOT NULL,
                CONSTRAINT novedades_variacion_permanente_salario_pk PRIMARY KEY (ID)
);


CREATE TABLE NOVEDADES_TRASLADO_AFP (
                ID BIGINT IDENTITY NOT NULL,
                ENTIDAD_DESTINO_AFP VARCHAR NOT NULL,
                CONSTRAINT novedades_traslado_afp_pk PRIMARY KEY (ID)
);


CREATE TABLE NOVEDADES_TRASLADO_EPS (
                ID BIGINT IDENTITY NOT NULL,
                ENTIDAD_DESTINO_EPS VARCHAR NOT NULL,
                CONSTRAINT novedades_traslado_eps_pk PRIMARY KEY (ID)
);

CREATE TABLE NOVEDADES_INCAPACIDAD_PROFESIONAL (
                ID BIGINT IDENTITY NOT NULL,
                DIA_INICIO_INCAPACIDAD_PROFESIONAL CHAR(2) NOT NULL,
                FECHA_FINAL DATE NOT NULL,
                CONSTRAINT novedades_incapacidad_profesional_pk PRIMARY KEY (ID)
);

CREATE TABLE NOVEDADES_APORTE_VOLUNTARIO (
                ID BIGINT IDENTITY NOT NULL,
                VALOR_APORTANTE INTEGER NOT NULL,
                VALOR_AFILIADO INTEGER NOT NULL,
                VALOR_NO_RETENIDO_APORTES INTEGER NOT NULL,
                CONSTRAINT novedades_aporte_voluntario_pk PRIMARY KEY (ID)
);

CREATE TABLE NOVEDADES_VACACIONES (
                ID BIGINT IDENTITY NOT NULL,
                DIA_INICIO_VACACIONES CHAR(2) NOT NULL,
                FECHA_FINAL_VACACIONES DATE NOT NULL,
                SALARIO_BASICO INTEGER NOT NULL,
                CONSTRAINT novedades_vacaciones_pk PRIMARY KEY (ID)
);

CREATE TABLE NOVEDADES_LICENCIA_MATERNIDAD (
                ID BIGINT IDENTITY NOT NULL,
                DIA_INICIO CHAR(2) NOT NULL,
                FECHA_FINAL DATE NOT NULL,
                VALOR INTEGER NOT NULL,
                NRO_AUTORIZACION CHAR(4) NOT NULL,
                CONSTRAINT novedades_licencia_maternidad_pk PRIMARY KEY (ID)
);

CREATE TABLE NOVEDADES_INCAPACIDAD_GENERAL (
                ID BIGINT IDENTITY NOT NULL,
                DIA_INICIO_INCAPACIDAD_GENERAL CHAR(2) NOT NULL,
                FECHA_FINAL_INCAPACIDAD DATE NOT NULL,
                NRO_AUTORIZACION CHAR(4) NOT NULL,
                VALOR INTEGER NOT NULL,
                APORTE_DOS_PRIMEROS_DIAS BOOLEAN NOT NULL,
                APORTE_A_PARTIR_TERCER_DIA BOOLEAN NOT NULL,
                APLICA_PRORROGA BOOLEAN NOT NULL,
                TIPO_INCAPACIDAD_AMBULATORIA_HOSPITALARIA BOOLEAN NOT NULL,
                CONSTRAINT novedades_incapacidad_general_pk PRIMARY KEY (ID)
);

CREATE TABLE NOVEDADES_INGRESO (
                ID INTEGER IDENTITY  NOT NULL,
                DIA_INGRESO INTEGER NOT NULL,
                CONSTRAINT novedades_ingreso_pk PRIMARY KEY (ID)
);

CREATE TABLE NOVEDADES_RETIRO (
                ID BIGINT IDENTITY NOT NULL,
                TIPO_RETIRO CHAR(1) NOT NULL,
                DIA_RETIRO INTEGER NOT NULL,
                CONSTRAINT novedades_retiro_pk PRIMARY KEY (ID)
);

CREATE TABLE NOVEDADES_VARIACION_CENTROS_DE_TRABAJO (
                ID BIGINT IDENTITY NOT NULL,
                NUEVO_CENTRO_DE_TRABAJO VARCHAR NOT NULL,
                CENTRO_TRABAJO BIGINT NOT NULL,
                CONSTRAINT novedades_variacion_centros_de_trabajo_pk PRIMARY KEY (ID)
);

ALTER TABLE NOVEDADES ADD CONSTRAINT novedades_suspension_temporal_contrato_novedades_fk
FOREIGN KEY (SUSPENSION_TEMPORAL_CONTRATO)
REFERENCES public.NOVEDADES_SUSPENSION_TEMPORAL_CONTRATO (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE NOVEDADES ADD CONSTRAINT novedades_variacion_transitoria_del_salario_novedades_fk
FOREIGN KEY (VARIACION_TRANSITORIA_SALARIO)
REFERENCES public.NOVEDADES_VARIACION_TRANSITORIA_DEL_SALARIO (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE NOVEDADES ADD CONSTRAINT novedades_variacion_permanente_salario_novedades_fk
FOREIGN KEY (VARIACION_PERMANENTE_SALARIO)
REFERENCES public.NOVEDADES_VARIACION_PERMANENTE_SALARIO (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE NOVEDADES ADD CONSTRAINT novedades_traslado_afp_novedades_fk
FOREIGN KEY (TRASLADO_AFP)
REFERENCES public.NOVEDADES_TRASLADO_AFP (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE NOVEDADES ADD CONSTRAINT novedades_traslado_eps_novedades_fk
FOREIGN KEY (TRASLADO_EPS)
REFERENCES public.NOVEDADES_TRASLADO_EPS (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE NOVEDADES ADD CONSTRAINT novedades_incapacidad_profesional_novedades_fk
FOREIGN KEY (INCAPACIDAD_PROFESIONAL)
REFERENCES public.NOVEDADES_INCAPACIDAD_PROFESIONAL (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE NOVEDADES ADD CONSTRAINT aporte_voluntario_novedades_fk
FOREIGN KEY (APORTE_VOLUNTARIO)
REFERENCES public.NOVEDADES_APORTE_VOLUNTARIO (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE NOVEDADES ADD CONSTRAINT novedades_vacaciones_novedades_fk
FOREIGN KEY (VACACIONES)
REFERENCES public.NOVEDADES_VACACIONES (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE NOVEDADES ADD CONSTRAINT novedades_licencia_maternidad_novedades_fk
FOREIGN KEY (LICENCIA_MATERNIDAD)
REFERENCES public.NOVEDADES_LICENCIA_MATERNIDAD (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE NOVEDADES ADD CONSTRAINT novedades_incapacidad_general_novedades_fk
FOREIGN KEY (INCAPACIDAD_GENERAL)
REFERENCES public.NOVEDADES_INCAPACIDAD_GENERAL (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE NOVEDADES ADD CONSTRAINT novedades_ingreso_novedades_fk
FOREIGN KEY (INGRESO)
REFERENCES public.NOVEDADES_INGRESO (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE NOVEDADES ADD CONSTRAINT novedades_retiro_novedades_fk
FOREIGN KEY (RETIRO)
REFERENCES public.NOVEDADES_RETIRO (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE NOVEDADES ADD CONSTRAINT cotizantes_novedades_fk
FOREIGN KEY (COTIZANTE_ID)
REFERENCES public.COTIZANTES (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;